import Head from "next/head";
import Image from "next/image";
import Sidebar from "../components/Sidebar";
import Feed from "../components/Feed";
import Widgets from "../components/Widgets";
// import styles from '../styles/Home.module.css'

export default function Home({ newsResults }) {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/public/Logo_of_Twitter.svg" /> */}
      </Head>

      <main className="flex min-h-screen mx-auto ">
        {/* Sidebar */}
        <Sidebar />
        {/* Feed */}

        <Feed />

        {/* Widgets */}
        <Widgets />
        {/* Modal */}
      </main>
    </div>
  );
}
