import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../components/Sidebar'
import Feed from '../components/Feed'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>

      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/public/Logo_of_Twitter.svg" /> */}
      </Head>

      <main className='flex min-h-screen max-w-7xl mx-auto '>

        {/* Sidebar */}
        <Sidebar />
        {/* Feed */}

        <Feed />

        {/* Widgets */}

        {/* Modal */}
      </main>
    </div>




  )
}
